
import {
  ClerkProvider
} from '@clerk/nextjs';
// import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
// import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans } from "next/font/google";
import { TRPCReactProvider } from '../trpc/client';

import { env } from '@/env';
import "./globals.css";

const nunitoSans = Nunito_Sans({
  variable: '--font-sans',
  subsets: ['latin'],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const queryClient = new QueryClient()

  return (
    // <QueryClientProvider client={queryClient}>
      <ClerkProvider publishableKey={env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
        <html lang="en" className={nunitoSans.variable}>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <TRPCReactProvider>
                {children}
            </TRPCReactProvider>
          </body>
        </html>
        {/* <ReactQueryDevtools initialIsOpen={false} /> */}
      </ClerkProvider>
    // </QueryClientProvider >
  );
}
